//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBC.Admin.Web {
    
    
    public partial class BaseForm {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new CSBC.Admin.Web.CSBCAdminMasterPage Master {
            get {
                return ((CSBC.Admin.Web.CSBCAdminMasterPage)(base.Master));
            }
        }
    }
}
