// <auto-generated />
namespace CSBC.Admin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class SponsorProfileID2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SponsorProfileID2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404032039587_SponsorProfileID2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
